### ISSUE TITLE
Address class

### ISSUE THREAD

**Issue by ChristofferQuick** [Sebastian-Noren/PoliceSystem#103]
The address class has two variables to refer to the street
- streetName
- streetNumber

The database only has street which means we should fix this. One suggestion we talked about would be to remove streetNumber and rename streetName to just street.

If you think this is a good idea then assign yourself and implement the change in **atleast** these two classes:
- Address
- AddressBuilder

There might be more classes that depend on the variables like RandomPersonGenerator, take a look around and change where it's needed.

**Comment by jsoutine** [comment]
I'm on it ;)

**Comment by jsoutine** [comment]
Done

**Comment by jsoutine** [comment]
there were changes made in random person generator too, including random address and randomperson
