### ISSUE TITLE
Maven dependencies

### ISSUE THREAD

**Issue by ChristofferQuick** [Sebastian-Noren/PoliceSystem#109]
We have a lot of different dependencies, I am not sure if we need them all. Perhaps a we should clean pom.xml a bit.

**Anyone brave enough? :-)**

**Comment by Sebastian-Noren** [comment]
Nooo I destroy program...I no goood

**Comment by jsoutine** [comment]
I'll do it. pom is my buddy now. Going in.

**Comment by jsoutine** [comment]
Done
