### ISSUE TITLE
Get the crimes when getting a suspect

### ISSUE THREAD

**Issue by Sebastian-Noren** [Sebastian-Noren/PoliceSystem#117]
When ew get a suspect we don´t get the crimes the person is suspected for from the table "suspect_has_crime".

Can use Fisher. That are suspected for two crimes. SSN= 196104035555

May be some type of list, A person can be suspected for more then one crime.

**Comment by ChristofferQuick** [comment]
The feature is not implemented yet and therefore its not working.

**Comment by ChristofferQuick** [comment]
#### To be clear:
There are no persons, regardless of type, with a crime record or suspect of a any crimes. This is due to the difference of implementation in issue #102 

Currently I am solving issue #102 and after that we can start adding crimes.
