### ISSUE TITLE
SSN bug

### ISSUE THREAD

**Issue by Sebastian-Noren** [Sebastian-Noren/PoliceSystem#118]
Some SSN are sometime cut out Fisher for exampel with SSN: 196104035555 will come out like 19610435555,

**Comment by ChristofferQuick** [comment]
Might be something bad with the function getPersonalNumber in PersonalNumber.java, line 49. Intellij is displaying a warning on line 55 regarding the case of both month and day < 10. Check it out

**Comment by Sebastian-Noren** [comment]
Fixed
